### PR TITLE
add support for stepped ranges

### PR DESCRIPTION
**Pull request by ananthakumaran**
Stepped ranges is a new feature introduced in Elixir 1.12.0 (still in
pre-release). Compared to other binary operators, the stepped ranges
is handled differently by Elixir parser. It's parsed as

```
{:.., [], [1, {:"//", 10, 2}]}
```

then transformed to

```
{:..//, [], [1, 10, 2]}
```

Since tree sitter doesn't have any facility to do AST transformation,
I left the AST nodes in the former structure.

### CODE REVIEW

**Comment by akash-akya** [comment]
It appears `(1..2)//2` is valid. Should we support it as well?

**Comment by ananthakumaran** [comment]
> It appears `(1..2)//2` is valid. Should we support it as well?

good catch. I am thinking of whether to define `//` as just a binary operator. The way it's handled by the [parser](https://github.com/elixir-lang/elixir/blob/de103c0f4e3240aa38967298ccb5f483a9e40c16/lib/elixir/src/elixir_parser.yrl#L722) seems ad-hoc and not sure it's still context-free grammar. 

The current implementation already has an issue with `foo..bar baz//bat`. It parses the expression as `(.. foo (// (call bar baz) bat))` instead of `(.. foo (call bar (// baz baz))`. Marking `//` as a normal binary op would fix the issue, but will not raise syntax error if `//` is not immediately preceded by `..`. [elixir_makeup](https://github.com/elixir-makeup/makeup_elixir/commit/a0cc37d29ae730977977ee5012969c9944691808) just seems to treat `//` as a binary operator.

**Comment by akash-akya** [comment]
I agree with making it as binary operator for now. Handling all cases appears complicated. Perhaps we might be able to address this better in future versions of tree-sitter?

**Comment by ananthakumaran** [comment]
> Perhaps we might be able to address this better in future versions of tree-sitter?

Not sure at this point

**Pull request merged**
